### ISSUE TITLE
Add Wallpaper#getLink()

### ISSUE THREAD

**Issue by Shadorc** [ivkos/wallhaven4j#2]
Hello

First of all, thanks for this amazing API ! It's really helpful.

It's not a issue but a request, it would be great to have a Wallpaper#getLink() method that returns the wallpaper link :
![joystick _ atari _ video_games _ minimalism _ ret_2017-09-24_22-27-05](https://user-images.githubusercontent.com/6506416/30786558-f23451da-a177-11e7-968d-c2a275be7c1d.png)

Thanks :)

**Comment by ivkos** [comment]
Thanks for the feature request. I implemented as `Wallpaper::getShortLink()`. 

Please update to v1.3.0:
https://github.com/ivkos/wallhaven4j/releases/tag/1.3.0
